[theme]
base            = "dark"
primaryColor    = "#C8F135"
backgroundColor = "#0D0F14"
secondaryBackgroundColor = "#1A1D24"
textColor       = "#F0F0F0"
font            = "sans serif"

[server]
# Streamlit Cloud gère headless automatiquement
headless        = true
enableCORS      = false
enableXsrfProtection = true

[browser]
# Désactive la télémétrie Streamlit
gatherUsageStats = false

[client]
# Évite le clignotement au rechargement
showErrorDetails = false
toolbarMode      = "minimal"
