# .streamlit/secrets.toml

# Les identifiants Spotify (attendus par spotify_service.py)
SPOTIFY_CLIENT_ID = "159243dad83a47c78ad1417d00ddb622"
SPOTIFY_CLIENT_SECRET = "2fe9f05bb4574881aec28ef46ef65c0a"

# Les identifiants Turso (attendus pour ta base de données)
TURSO_DATABASE_URL = "libsql://kitospotify-rbk-group.aws-eu-west-1.turso.io"
TURSO_AUTH_TOKEN = "eyJhbGciOiJFZERTQSIsInR5cCI6IkpXVCJ9.eyJhIjoicnciLCJpYXQiOjE3ODIyMDIwNzAsImlkIjoiMDE5ZWYzN2YtNDUwMS03YTdhLWI3NWQtMDNkNTk2NTU0YzhiIiwicmlkIjoiMTAxNWRlZmYtMzBjNi00OGY2LTk0MmQtMjNiNjkwNmIwNWNjIn0.ZFUYrdakSZNyRuxM2TSxUd6bhwjtrqygf2IFdOiMV3sm11N8grVal1EI722BCkaVDTrs8-j4Ja-dwZNFN1lWBw"